<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-VDDHET5" failures="10" tests="15" name="Data Driven Test" time="185.322" errors="0" timestamp="2025-07-13T10:56:13 IST">
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="4.147"/>
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="7.241"/>
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="13.114">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_DataDrivenTest.dataDrivenTest(TC003_DataDrivenTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="11.481">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_DataDrivenTest.dataDrivenTest(TC003_DataDrivenTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="21.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_DataDrivenTest.dataDrivenTest(TC003_DataDrivenTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="6.996"/>
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="12.732">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_DataDrivenTest.dataDrivenTest(TC003_DataDrivenTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="12.666">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_DataDrivenTest.dataDrivenTest(TC003_DataDrivenTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="13.37">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_DataDrivenTest.dataDrivenTest(TC003_DataDrivenTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="5.148"/>
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="11.377">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_DataDrivenTest.dataDrivenTest(TC003_DataDrivenTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="10.886">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_DataDrivenTest.dataDrivenTest(TC003_DataDrivenTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="5.465"/>
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="12.952">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_DataDrivenTest.dataDrivenTest(TC003_DataDrivenTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
  <testcase classname="testCases.TC003_DataDrivenTest" name="dataDrivenTest" time="12.816">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_DataDrivenTest.dataDrivenTest(TC003_DataDrivenTest.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataDrivenTest -->
</testsuite> <!-- Data Driven Test -->
